@startuml

'Initiator start'
:Initiator: -> (Pick Image)

'Common flow'
(Pick Image) -> (Take a Shot) : Camera
(Pick Image) --> (Choose from library)
(Take a Shot) -> (Preview)
(Choose from library) --> (Preview)
(Share Bill) <.. (Preview) : Initiator
''(Preview) ..> (Share Bill) : Initiator
(Preview) .> (Edit Bill) : Invitee\ngoes directly
(Preview) .> (Pick Image) : Discard

'Share bill Screen'
''(Share Bill) <-> (Describe Bill)
''(Share Bill) <-> (Add Geo Tag)
''(Share Bill) <- (Share Bill) : Choose\ninvitees
:Invitee: <- (Share Bill) : Invite

'Invitee start'
:Invitee: -> (Receive Invitation)
(Receive Invitation) --> (Edit Bill)

newpage

''(Share Bill) ->

@enduml
